services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faberorg_web
    command: ["gunicorn", "faberorg.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - faberorg-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: faberorg
      POSTGRES_PASSWORD: password
      POSTGRES_DB: faberorg
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - faberorg-network

networks:
  faberorg-network:
    driver: bridge

volumes:
  postgres_data:
