# Generated by Django 5.2.6 on 2025-10-19 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_groups', to='core.project')),
            ],
            options={
                'ordering': ['project', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('working_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='core.workinggroup')),
            ],
            options={
                'ordering': ['working_group', 'name'],
                'unique_together': {('working_group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TopicMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation_level', models.CharField(choices=[('subscriber', 'Subscriber'), ('contributor', 'Contributor'), ('leader', 'Leader')], default='subscriber', max_length=20)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic', 'user'],
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='WorkingGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation_level', models.CharField(choices=[('subscriber', 'Subscriber'), ('contributor', 'Contributor'), ('leader', 'Leader')], default='subscriber', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('working_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.workinggroup')),
            ],
            options={
                'ordering': ['working_group', 'user'],
                'unique_together': {('user', 'working_group')},
            },
        ),
    ]
